export const CATEGORIES_ACTION_TYPES = {
	FETCH_CATEGORIES_START: 'category/FFETCH_CATEGORIES_START',
	FETCH_CATEGORIES_SUCCESS: 'category/FFETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_FAILED: 'category/FFETCH_CATEGORIES_FAILED',
};
